### PR TITLE
Update addons_lang.php

### PR DESCRIPTION
**Pull request by bytebaby**
I hope, this file is ready to work for german customers ;) 

At the moment I work on the file "admin_content_lang" (it's really long ;) and I have some question about the following line:

’checkbox_options_desc' => '`<em><i>`Each item in the textarea will generate a single checkbox and label pair in the publish form.`</i>`',

- Where can I find the row in the backend?
- Is `<em>` and `<i>` neccessary or they can get away?

Thank you

### CODE REVIEW

**Comment by bytebaby** [comment]
The questions have been answered. :)

**Comment by bytebaby** [comment]
Hi Kevin,

As I continue to work enthusiastically on the language files, it would be great if you could give me the filenames that have changed for version 4.1. Currently I am working at cp_lang.php - I am working alphabetically. 

Thanks & Greetings,
Ralph

**Comment by kevincupp** [comment]
Hey Ralph,

Sure, here’s all the files that have changed since 4.0.9 and what’s changed
inside of them:

https://github.com/EllisLab/EE-Language-English/compare/4.0.9...4.1.0

Thank you!!

Kevin



On March 2, 2018 at 10:20:38 AM, Ralph Segert (notifications@github.com)
wrote:

Hi Kevin,

As I continue to work enthusiastically on the language files, it would be
great if you could give me the filenames that have changed for version 4.1.
Currently I am working at cp_lang.php - I am working alphabetically.

Thanks & Greetings,
Ralph


—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/EllisLab/EE-Language-German/pull/119#issuecomment-369949935>,
or mute the thread

**Comment by bytebaby** [comment]
Great, and an easy way to stay up-to-date. Thank you!

Ralph

**Pull request merged**
