### PR TITLE
Update core_lang.php

### PR DESCRIPTION
**Pull request by bytebaby**

### CODE REVIEW

**Comment by kevincupp** [comment]
Thanks again, Ralph!!

**Comment by bytebaby** [comment]
Hi Kevin,

I again. In which file can I find the word for the filters:



Thanks :)

Regards,
Ralph

— 

Appverstand
Ralph Segert
User Interface Design und Webentwicklung
Dreihügelstraße 41d
D-44805 Bochum

Fon    +49 234 62 347 200
Mobil  +49 162 42 744 62
  
Web    http://appverstand.com
Eamil  segert@verstand.io

**Comment by kevincupp** [comment]
"Filters" should be in cp_lang.php.

**Comment by bytebaby** [comment]
Unfortunately, not. Also not in English file

Ralph

**Comment by kevincupp** [comment]
It's here:

https://github.com/EllisLab/EE-Language-English/blob/master/user/language/english/cp_lang.php#L307

Is that not what you're looking for?

**Comment by bytebaby** [comment]
I mean:




:-)

**Comment by bytebaby** [comment]
Hi Kevin,

I don’t have a Email-Adresse from you, that's why I respond to these thread.

I don’t find the file of this part from the CP-Interface:






And perhaps, do you have an idea, which file contains the following words? It would be great:
My reason: It's better to write the following words: Channel, Kategorie, Status etc.






Thank you for your patience :)


Best regards,
Ralph

— 

  APPVERSTAND
  Ralph Segert
  User Interface Design und Webentwicklung
  Dreihügelstraße 41d
  D-44805 Bochum

  Fon    +49 234 62 347 200
  Mobil  +49 162 42 744 62
  
  Web    http://appverstand.com
  Email  segert@verstand.io

  UST-ID: DE204584833
  Finanzamt Bochum

**Comment by kevincupp** [comment]
Hi Ralph, did you attach images or something? They didn't come through on GitHub. Click through to the web interface to see what I see.

**Comment by bytebaby** [comment]
Yes, I did:
[which-language-files](https://cloud.githubusercontent.com/assets/21154749/23413557/546bed9c-fdd9-11e6-9ee4-e3c90ae34f1a.png)

**Comment by bytebaby** [comment]
Now I understand why I couldn't find it.  Unfortunately it is absent in the German files. Thank you.

**Comment by kevincupp** [comment]
Typically what the language pack maintainers do is when we release, check our English repo to see what has changed using the links in the README:

https://github.com/EllisLab/EE-Language-English

They then update their language packs. Probably since the German one wasn't maintained for a while, it got out of sync. There isn't really an easy way now except to manually compare the files, unfortunately.

**Comment by bytebaby** [comment]
I've searched all files: The words such as "kategorie", "status", "zeigen" etc. (look the screenshot) are definitely in no language file in the directory "deutsch".

**Comment by kevincupp** [comment]
I looked at the screenshot and even linked you to the exact line and file for those items in the Deutsch repo, I'm not sure what more to tell you.

Again, here are 'kategorie' and 'status':
https://github.com/EllisLab/EE-Language-German/blob/master/system/user/language/deutsch/content_lang.php#L11

Zeigen is later in that same file:

https://github.com/EllisLab/EE-Language-German/blob/master/system/user/language/deutsch/content_lang.php#L772

Are you saying you are changing those items but it is not reflecting in the control panel?

**Comment by bytebaby** [comment]
But there is a difference, the first letter is an uppercase letter: "K"ategorie or "S"tatus 
But in the CP-Interface is the first letter a lowercase letter, so "k"ategorie or "s"tatus.
Why? :)

**Comment by kevincupp** [comment]
Because it's a style choice. The text is transformed in the presentation layer, we typically try not to bring those kinds of style choices into the language files.

**Comment by bytebaby** [comment]
Ok, I understand. But I think, Capitalization would be the right choice for the German language for these words. :-)

**Comment by kevincupp** [comment]
Ok I checked with our designer and he said I could change this for you. We'll get it out in the next patch release so that we're not automatically making those labels lower case.

**Comment by bytebaby** [comment]
It's great. Thanks!

**Pull request merged**
