### PR TITLE
Update sites_lang.php

### PR DESCRIPTION
**Pull request by bytebaby**

### CODE REVIEW

**Comment by kevincupp** [comment]
Thanks!!

**Comment by bytebaby** [comment]
Hi Kevin,

I am not satisfied with the German language pack. Compared with the englische version is a lot confusion. I am planning to create a completely new German language pack für EE4 -  independently from GitHub. 

Makes it sense to take the English language package as a template, then new to translate all? I will try it. Then once everything was done and could be offered for download. What do you think about that.


Schönen Gruß,
Ralph

— 

  RALPH SEGERT
  User Interface Design & Content Management
  Dreihügelstraße 41d
  D-44805 Bochum

  Fon    +49 234 62 347 200
  Mobil  +49 162 42 744 62
  
  Web    https://segert.net
  Email  arbeit@segert.net

  UST-ID: DE204584833
  Finanzamt Bochum

**Comment by kevincupp** [comment]
Sorry about that, I’m sure the reformatting and alphabetizing has made things difficult. If you create a new language pack, you can still submit it to GitHub, if you like. For instance, someone recently re-formatted the French language pack to be more consistent with the English version and submitted it to us:

https://github.com/EllisLab/EE-Language-French/pull/28/files

If that’s the direction you’re going, maybe you can still submit it to GitHub?

**Comment by ebeauchamps** [comment]
Well, actually I have been working on the French language pack for years now, so it makes things a little more easier...

For me, it makes sense to start with an almost new translation because if you want to go the way the English files have now gone (keys sorted alphabetically, though it is not always consistent) you will encounter difficulties merging your changes in Github: you will probably get many merge conflicts.

First, create a 3.x branch to "ice" this version, then start working by ALWAYS comparing one English file with the German one. TextWrangler is really the greatest tool to compare 2 files side by side or to make coherent changes throughout many files.

Creating the 3.x version from (almost) scratch (2.7 version) took me 3 months (1 to 3 hours a day), but creating the 4.x version from the latest 3.x took me one week.

But I am pretty sure German (and Dutch) are the 2 most-wanted language for EE in Europe, so you work will probably be very appreciated!

Good luck!

**Comment by bytebaby** [comment]
Merci pour l’information. I am trying to translate a file every day. I'm currently working on addons_lang.php.  I take the English language version of 4.0.7 as template. And translate newly in German. Linguistic consistency is important to me. Write always and in every file "Add-On“ for example. I want to write user friendly with good explanations. That's a lot of work, but if it is done, we all are happy. ;-)

My question is now: How can I set up a new branch of Github as well as "French translation Pack for ExpressionEngine 4.x“. Thus "German translation Pack for ExpressionEngine 4.x“.

I will try TextWrangler, I usually use Coda. ;)
 
Regards,
Ralph

**Comment by bytebaby** [comment]
Yes, I would submit that also like to Github. 

I have a contact if I have questions? For example in addons_lang.php:

'extension_class_does_not_exist' => 'Class %c does not exist in (%f)‘,

What means „Class“ ?

or

Is „extension“ and „Add-On" not the same? I can’t find an extension manager in the backend.

Can I collect a series of questions and then at once submit?

Thanx :)

**Comment by kevincupp** [comment]
There is already a 3.x branch for this repo, so you can go ahead and just use the master branch.

Sure, feel free to contact us if you have questions. A class in that case is a are in the [PHP programming sense](http://php.net/manual/en/language.oop5.basic.php). And an Add-on typically refers to an entire add-on package, whereas an extension is a particular piece of an add-on that performs tasks by hooking into certain system events. We got rid of the extension manager starting in 3.x.

**Comment by ebeauchamps** [comment]
Hi Ralph.
To answer your previous question, as you are on the Master branch (therefore the fastest branch) you "just" have to make changes to the Readme file which is part of your repository in order to put, for example, "German language pack for EE 4.x" or something similar.
Emmanuel

**Comment by bytebaby** [comment]
Hi Emmanuel,

cool. Thanks for your help. I hope, now I understand :) - I know not well with Github, mais j’apprends tous les jours.

Kevin, then, it makes sense not to translate the term „extension" because it is intended for developers. Right?  

Beautiful Sunday still :)
Ralph

**Comment by kevincupp** [comment]
Yes a typical editor shouldn't really have to differentiate between extensions, modules, plugins, etc. That's why we concentrated them all under one place: the Add-On Manager

Thanks for your help, everyone!!

**Pull request merged**
